//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordTicker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordTicker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AARON
        ///ABACK
        ///ABAFT
        ///ABASE
        ///ABASH
        ///ABATE
        ///ABBEY
        ///ABBOT
        ///ABEAM
        ///ABETS
        ///ABHOR
        ///ABIDE
        ///ABODE
        ///ABORT
        ///ABOUT
        ///ABOVE
        ///ABUSE
        ///ABUTS
        ///ABYSS
        ///ACCRA
        ///ACHED
        ///ACHES
        ///ACIDS
        ///ACORN
        ///ACRES
        ///ACRID
        ///ACRYL
        ///ACTED
        ///ACTON
        ///ACTOR
        ///ACUTE
        ///ADAGE
        ///ADAMS
        ///ADAPT
        ///ADDED
        ///ADDER
        ///ADDLE
        ///ADEPT
        ///ADIEU
        ///ADLER
        ///ADMAN
        ///ADMIT
        ///ADMIX
        ///ADOPT
        ///ADORE
        ///ADORN
        ///ADULT
        ///AEGIS
        ///AEONS
        ///AESOP
        ///AFFIX
        ///AFIRE
        ///AFOOT
        ///AFORE
        ///AFOUL
        ///AFTER
        ///AGAIN
        ///AGANA
        ///AGAPE
        ///AGATE
        ///AGENT
        ///AGGRO
        ///AGILE
        ///AGLOW
        ///AGNES
        ///AGONY
        ///AGORA
        ///AGREE
        ///AGUES
        ///AHEAD
        ///AIDED
        ///AIDER
        ///AIDES
        ///AILED
        ///AIMED
        ///AIRED
        ///AISLE
        ///ALAMO
        ///ALARM
        ///ALBUM
        ///ALDER
        ///ALERT
        ///ALGAE
        ///ALIAS
        ///ALIBI
        ///AL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string words {
            get {
                return ResourceManager.GetString("words", resourceCulture);
            }
        }
    }
}
